"""empty message

Revision ID: e5309802b156
Revises: 
Create Date: 2020-12-20 21:50:46.129230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5309802b156'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_cliente', sa.Column('tipo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario_cliente', 'tipo')
    # ### end Alembic commands ###
